kind: ConfigMap
apiVersion: v1
metadata:
  name: telegraf-config
  namespace: newton
  uid: 596085fc-0ea7-45ca-9da0-d82a11bf4d23
  resourceVersion: '9860531'
  creationTimestamp: '2022-09-30T06:05:32Z'
  labels:
    kubernetes.io/metadata.name: newton
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-09-30T06:23:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:telegraf.conf': {}
        'f:metadata':
          'f:labels':
            .: {}
            'f:kubernetes.io/metadata.name': {}
data:
  telegraf.conf: |-
    [[processors.regex]]
      [[processors.regex.fields]]
        key = "log-dates"
        pattern = "^(?P<YYYY>\\d{4})(?P<MM>\\d{2})(?P<DD>\\d{2})(?P<HH>\\d{2})(?P<mm>\\d{2})(?P<ss>\\d{2})\\.(?P<SSSSSS>\\d{6})(?P<ZZ>[-+]\\d{3,4})$"
        replacement = "${YYYY}-${MM}-${DD} ${HH}:${mm}:${ss}"

    [[inputs.snmp]]
      agents = [ "udp://192.168.52.167:161" ,
                 "udp://192.168.52.168:161" ,
                 "udp://192.168.52.169:161", 
                 "udp://192.168.52.150:161" ,
                 "udp://192.168.52.151:161" ,
                 "udp://192.168.52.173:161",
                 "udp://192.168.52.172:161" ]
                 #w3                            #w4                           #w2                             #SNO
     #agents = [ "udp://192.168.52.150:161" , "udp://192.168.52.151:161" , "udp://192.168.52.173:161", "udp://192.168.52.172:161"]
      version = 1
      community = "public"
      name = "idrac-hosts"

      [[inputs.snmp.field]]
        name = "system-name"
        oid  = ".1.3.6.1.2.1.1.5.0"
        is_tag = true

      [[inputs.snmp.field]]
        name = "system-osname"
        oid  = ".1.3.6.1.4.1.674.10892.5.1.3.6.0"

      [[inputs.snmp.field]]
        name = "system-osversion"
        oid  = ".1.3.6.1.4.1.674.10892.5.1.3.14.0"

      [[inputs.snmp.field]]
        name = "system-model"
        oid  = ".1.3.6.1.4.1.674.10892.5.1.3.12.0"

      [[inputs.snmp.field]]
        name = "idrac-url"
        oid  = ".1.3.6.1.4.1.674.10892.5.1.1.6.0"

      [[inputs.snmp.field]]
        name = "power-state"
        oid  = ".1.3.6.1.4.1.674.10892.5.2.4.0"

      [[inputs.snmp.field]]
        name = "system-uptime"
        oid  = ".1.3.6.1.4.1.674.10892.5.2.5.0"

      [[inputs.snmp.field]]
        name = "system-servicetag"
        oid  = ".1.3.6.1.4.1.674.10892.5.1.3.2.0"

      [[inputs.snmp.field]]
        name = "system-globalstatus"
        oid  = ".1.3.6.1.4.1.674.10892.5.2.1.0"

      [[inputs.snmp.table]]
        name = "idrac-hosts"
        inherit_tags = [ "system-name" , "disks-name" ]

        [[inputs.snmp.table.field]]
          name = "bios-version"
          oid = ".1.3.6.1.4.1.674.10892.5.4.300.50.1.8"

        [[inputs.snmp.table.field]]
          name = "raid-batterystate"
          oid = ".1.3.6.1.4.1.674.10892.5.5.1.20.130.15.1.4"

        [[inputs.snmp.table.field]]
          name = "intrusion-sensor"
          oid = ".1.3.6.1.4.1.674.10892.5.4.300.70.1.6"

        [[inputs.snmp.table.field]]
          name = "disks-mediatype"
          oid = ".1.3.6.1.4.1.674.10892.5.5.1.20.130.4.1.35"

        [[inputs.snmp.table.field]]
          name = "disks-state"
          oid = ".1.3.6.1.4.1.674.10892.5.5.1.20.130.4.1.4"

        [[inputs.snmp.table.field]]
          name = "disks-predictivefail"
          oid = ".1.3.6.1.4.1.674.10892.5.5.1.20.130.4.1.31"

        [[inputs.snmp.table.field]]
          name = "disks-capacity"
          oid = ".1.3.6.1.4.1.674.10892.5.5.1.20.130.4.1.11"

        [[inputs.snmp.table.field]]
          name = "disks-name"
          oid = ".1.3.6.1.4.1.674.10892.5.5.1.20.130.4.1.2"
          is_tag = true

        [[inputs.snmp.table.field]]
          name = "memory-status"
          oid = ".1.3.6.1.4.1.674.10892.5.4.200.10.1.27"

        [[inputs.snmp.table.field]]
          name = "storage-status"
          oid = ".1.3.6.1.4.1.674.10892.5.2.3"

        [[inputs.snmp.table.field]]
          name = "temp-status"
          oid = ".1.3.6.1.4.1.674.10892.5.4.200.10.1.63"

        [[inputs.snmp.table.field]]
          name = "psu-status"
          oid = ".1.3.6.1.4.1.674.10892.5.4.200.10.1.9"

        [[inputs.snmp.table.field]]
          name = "log-dates"
          oid = ".1.3.6.1.4.1.674.10892.5.4.300.40.1.8"

        [[inputs.snmp.table.field]]
          name = "log-entry"
          oid = ".1.3.6.1.4.1.674.10892.5.4.300.40.1.5"

        [[inputs.snmp.table.field]]
          name = "log-severity"
          oid = ".1.3.6.1.4.1.674.10892.5.4.300.40.1.7"

        [[inputs.snmp.table.field]]
          name = "log-number"
          oid = ".1.3.6.1.4.1.674.10892.5.4.300.40.1.2"
          is_tag = true

        [[inputs.snmp.table.field]]
          name = "nic-name"
          oid = ".1.3.6.1.4.1.674.10892.5.4.1100.90.1.30"
          is_tag = true

        [[inputs.snmp.table.field]]
          name = "nic-vendor"
          oid = ".1.3.6.1.4.1.674.10892.5.4.1100.90.1.7"

        [[inputs.snmp.table.field]]
          name = "nic-status"
          oid = ".1.3.6.1.4.1.674.10892.5.4.1100.90.1.4"

        [[inputs.snmp.table.field]]
          name = "nic-current_mac"
          oid = ".1.3.6.1.4.1.674.10892.5.4.1100.90.1.15"
          conversion = "hwaddr"

      [[inputs.snmp.field]]
        name = "fan1-speed"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.1"

      [[inputs.snmp.field]]
        name = "fan2-speed"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.2"

      [[inputs.snmp.field]]
        name = "fan3-speed"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.3"

      [[inputs.snmp.field]]
        name = "fan4-speed"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.4"

      [[inputs.snmp.field]]
        name = "fan5-speed"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.5"

      [[inputs.snmp.field]]
        name = "fan6-speed"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.700.12.1.6.1.6"

      [[inputs.snmp.field]]
        name = "inlet-temp"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.700.20.1.6.1.1"

      [[inputs.snmp.field]]
        name = "exhaust-temp"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.700.20.1.6.1.2"

      [[inputs.snmp.field]]
        name = "cpu1-temp"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.700.20.1.6.1.3"

      [[inputs.snmp.field]]
        name = "cpu2-temp"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.700.20.1.6.1.4"

      [[inputs.snmp.field]]
        name = "cmos-batterystate"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.600.50.1.6.1.1"

      [[inputs.snmp.field]]
        name = "system-watts"
        oid  = ".1.3.6.1.4.1.674.10892.5.4.600.30.1.6.1.3"
    [[outputs.file]]
      files = ["stdout", "/tmp/metrics.out"]

    [[outputs.prometheus_client]]
        ## Address to listen on.
        listen = "0.0.0.0:9090"

        ## Use HTTP Basic Authentication.
        # basic_username = "Foo"
        # basic_password = "Bar"
        metric_version = 2
        ## If set, the IP Ranges which are allowed to access metrics.
        ##   ex: ip_range = ["192.168.0.0/24", "192.168.1.0/30"]
        # ip_range = []

        ## Path to publish the metrics on.
        path = "/metrics"

        ## Expiration interval for each metric. 0 == no expiration
        #expiration_interval = "0s"

        ## Collectors to enable, valid entries are "gocollector" and "process".
        ## If unset, both are enabled.
        # collectors_exclude = ["gocollector", "process"]

        ## Send string metrics as Prometheus labels.
        ## Unless set to false all string metrics will be sent as labels.
        # string_as_label = true

        ## If set, enable TLS with the given certificate.
        # tls_cert = "/etc/ssl/telegraf.crt"
        # tls_key = "/etc/ssl/telegraf.key"

        ## Export metric collection time.
        export_timestamp = true
